std = "selene-defs"
exclude = [
  "*.d.luau",
  ".pesde/*",
  "roblox_packages/*",
  "luau_packages/*",
  "lune_packages/*",
  "src/network/*",
]

[lints]
almost_swapped = "deny"
constant_table_comparison = "deny"
deprecated = "deny"
divide_by_zero = "deny"
duplicate_keys = "deny"
empty_if = "warn"
empty_loop = "warn"
global_usage = "deny"
high_cyclomatic_complexity = "warn"
if_same_then_else = "deny"
ifs_same_cond = "deny"
incorrect_standard_library_use = "deny"
manual_table_clone = "deny"
mismatched_arg_count = "deny"
mixed_table = "allow"
multiple_statements = "deny"
must_use = "deny"
parenthese_conditions = "deny"
roblox_incorrect_color3_new_bounds = "deny"
roblox_incorrect_roact_usage = "deny"
roblox_suspicious_udim2_new = "deny"
shadowing = "deny"
suspicious_reverse_loop = "deny"
type_check_inside_call = "deny"
unbalanced_assignments = "deny"
undefined_variable = "deny"
unscoped_variables = "deny"
unused_variable = "deny"

[config]
deprecated = { allow = [] }
empty_if = { comments_count = true }
empty_loop = { comments_count = true }
high_cyclomatic_complexity = { maximum_complexity = 20 }
multiple_statements = { one_line_if = "deny" }
shadowing = { ignore_pattern = "^_|..." }
unscoped_variables = { ignore_pattern = "^_|..." }
unused_variable = { allow_unused_self = true, ignore_pattern = "^_|..." }
global_usage = { ignore_pattern = "^__" }
